---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: final-project
  region: "us-east-1"
  version: "1.26"

availabilityZones: ["us-east-1a" ,"us-east-1b" ,"us-east-1c"]
iam:
  serviceRoleARN: arn:aws:iam::655028241628:role/LabRole
managedNodeGroups:
- name: final
  desiredCapacity: 2
  instanceType: t3.small
  ssh:
    enableSsm: true
  iam:
    instanceRoleARN: arn:aws:iam::655028241628:role/LabRole
