apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: final
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 8080     # Port your Flask app is running on inside the pod
      targetPort: 81 # Port your Flask app is listening on inside the pod
  type: LoadBalancer