apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: 655028241628.dkr.ecr.us-east-1.amazonaws.com/app:myapp
        ports:
        - containerPort: 8080
        env:
          - name: DBHOST
            value: "mysql-service"  # This should match the service name of your MySQL deployment
          - name: DBPORT
            value: "3306"  # MySQL default port
          - name: DBUSER
            valueFrom:
              secretKeyRef:
                name: db-secret  # This is the name of the secret you'll create
                key: username
          - name: DBPWD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: password
          - name: DATABASE
            value: "mysql" 
          - name: background_image_location
            valueFrom:
              configMapKeyRef:
                name: app-configmap
                key: background-image-location
