apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: 655028241628.dkr.ecr.us-east-1.amazonaws.com/final:application
        ports:
        - containerPort: 81
        env:
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DBUSER
        - name: DBHOST
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DBHOST
        - name: DBPWD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DBPWD
        - name: DATABASE
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DATABASE
        - name: background_image_location
          valueFrom:
            configMapKeyRef:
              name: app-configmap
              key: background-image-location
        - name: DBPORT
          value: "3306"
