apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: clo835-rolebinding
subjects:
- kind: ServiceAccount
  name: clo835
  namespace: default
roleRef:
  kind: Role
  name: clo835-role
  apiGroup: rbac.authorization.k8s.io