apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: final
  name: secret-reader-rolebinding
subjects:
- kind: ServiceAccount
  name: clo835
  namespace: final
roleRef:
  kind: Role
  name: secret-reader-role
  apiGroup: rbac.authorization.k8s.io