apiVersion: v1
kind: Pod
metadata:
  name: my-app
spec:
  containers:
  - name: my-app-container
    image: my-app-image
    env:
      - name: DBUSER
        valueFrom:
          secretKeyRef:
            name: mysql-credentials
            key: DBUSER
      - name: DBPWD
        valueFrom:
          secretKeyRef:
            name: mysql-credentials
            key: DBPWD
      - name: DBHOST
        valueFrom:
          secretKeyRef:
            name: mysql-credentials
            key: DBHOST
      - name: DATABASE
        valueFrom:
          secretKeyRef:
            name: mysql-credentials
            key: DATABASE
      - name: DBPORT
        valueFrom:
          secretKeyRef:
            name: mysql-credentials
            key: DBPORT
